In [ ]:
import pandas as pd
import re
import numpy as np


df = pd.read_csv('dataset_sintetico_regex_ruidos.csv')
# ============================================
# 🧠 Análise de Dados Textuais com Regex
# Autor: Jefté Damaceno de Moura
# ============================================



# ============================
# ETAPA 1 — CARREGAMENTO E EXPLORAÇÃO
# ============================


# Visualizar as primeiras linhas
print("📊 Visualização inicial do dataset:")
display(df.head())

# Ver informações básicas
print("\n📋 Informações gerais:")
print(df.info())

# ============================
# ETAPA 2 — CRIAÇÃO DE PADRÕES REGEX
# ============================

padroes = {
    "nome": r"^[A-ZÁÉÍÓÚÂÊÔÃÕÇ][a-záéíóúâêôãõç]+(\s[A-ZÁÉÍÓÚÂÊÔÃÕÇ][a-záéíóúâêôãõç]+)+$",
    "cpf": r"^\d{3}\.?\d{3}\.?\d{3}-?\d{2}$",
    "cnpj": r"^\d{2}\.?\d{3}\.?\d{3}/?\d{4}-?\d{2}$",
    "email": r"^[\w\.-]+@[\w\.-]+\.\w+$",
    "telefone": r"^\(?\d{2}\)?\s?\d{4,5}-?\d{4}$",
    "cep": r"^\d{5}-?\d{3}$",
    "data": r"^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/[0-9]{4}$",
    "valor": r"^R\$ ?\d{1,3}(\.\d{3})*,\d{2}$"
}

# ============================
#  TESTE DOS PADRÕES
# ============================

def testar_regex(coluna, padrao):
    """Retorna se o valor está válido (True) ou não (False) com base no regex."""
    return df[coluna].apply(lambda x: bool(re.fullmatch(padrao, str(x).strip())))

# Aplica os padrões a todas as colunas que existirem no dataset
resultados = {}
for campo, padrao in padroes.items():
    if campo in df.columns:
        resultados[campo] = testar_regex(campo, padrao)
        print(f"\n🔍 Resultados para '{campo}':")
        print(resultados[campo].value_counts())

# ============================
#  RELATÓRIO DE QUALIDADE
# ============================

print("\n📈 RELATÓRIO DE CAMPOS INVÁLIDOS:")
for campo, validacoes in resultados.items():
    invalidos = df[~validacoes]
    if len(invalidos) > 0:
        print(f"\n❌ {campo.upper()} - {len(invalidos)} inválidos")
        display(invalidos[[campo]].head())
    else:
        print(f"\n✅ {campo.upper()} - Todos os valores estão válidos!")

📊 Visualização inicial do dataset:

,nome,email,telefone,cpf,cnpj,cep,data,valor,url,texto_livre
0,Danielë Souza,o ig8f_1c@example.com,(71) 959440-7816,999.9299.9999-99,86.379.402/6542-35,84959-310,331/07/203,"R$5 3.553,18",http://site.org/3xkxw/rek8,Cliente: Danielë Souza Contato: o ig8f_1c@exam...
1,S érgi8 Rodrigues,87a+u5b@,+55 71 57871ê331,43039117b122,2 27824-9638308,09839301,33/6/1994,141.556,h ttps://exemplo.com/n8i4p4/mgg1w11/3dgdzv,Cliente: S érgi8 Rodrigues Contato: 87a+u5b@ |...
2,H elena Costa,3uea3-.geû@ufc.br,3191824-4935,5555555555,54278498084187,48740164,13//11/2005,"_1,371.3",http://sitee.org/919ah,Cliente: H elena Costa Contato: 3uea3-.geû@ufc...
3,Yasmin Martins,c1a7mx1e@gmail com,(98) 95777-3872,951.484.656-70,36.629.946/8044-38,4895343,3 9/088/2029,"R $ 3.497,38",http://site.orrg/my5zpj/g1o,Cliente: Yasmin Martins Contato: c1a7mx1e@gmai...
4,Natan Azevedo,-8bz_.b@example.com,+55(92)90330-9232,272.0946.537-26,64641708053143,1 9374-5229,1 9/02/2005,R$ 777.92,https://contato.me/bty/mepgth,Cliente: Natan Azevedo Contato: -8bz_.b@exampl...

📋 Informações gerais:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   nome         1000 non-null   object
 1   email        1000 non-null   object
 2   telefone     1000 non-null   object
 3   cpf          1000 non-null   object
 4   cnpj         1000 non-null   object
 5   cep          1000 non-null   object
 6   data         1000 non-null   object
 7   valor        1000 non-null   object
 8   url          1000 non-null   object
 9   texto_livre  1000 non-null   object
dtypes: object(10)
memory usage: 78.3+ KB
None

🔍 Resultados para 'nome':
nome
True     578
False    422
Name: count, dtype: int64

🔍 Resultados para 'cpf':
cpf
False    655
True     345
Name: count, dtype: int64

🔍 Resultados para 'cnpj':
cnpj
False    642
True     358
Name: count, dtype: int64

🔍 Resultados para 'email':
email
False    547
True     453
Name: count, dtype: int64

🔍 Resultados para 'telefone':
telefone
False    758
True     242
Name: count, dtype: int64

🔍 Resultados para 'cep':
cep
False    669
True     331
Name: count, dtype: int64

🔍 Resultados para 'data':
data
False    720
True     280
Name: count, dtype: int64

🔍 Resultados para 'valor':
valor
False    969
True      31
Name: count, dtype: int64

📈 RELATÓRIO DE CAMPOS INVÁLIDOS:

❌ NOME - 422 inválidos

                 nome
0       Danielë Souza
1  S  érgi8 Rodrigues
2      H  elena Costa
5          Paulo osta
7     M  arin Ribeiro

❌ CPF - 655 inválidos

                cpf
0  999.9299.9999-99
1      43039117b122
2        5555555555
4   272.0946.537-26
9      333333333333

❌ CNPJ - 642 inválidos

                    cnpj
1       2  27824-9638308
6   3  4.824.771/0322-96
7        74821759464755-
8  7  1.390.053/293j1-83
9    99.809.402/4ã455-67

❌ EMAIL - 547 inválidos

                     email
0   o  ig8f_1c@example.com
1                 87a+u5b@
3       c1a7mx1e@gmail com
12            2  +1k2w2cw@
13   .  cbfc.qn.0@uu(fc.br

❌ TELEFONE - 758 inválidos

            telefone
0   (71) 959440-7816
1   +55 71 57871ê331
4  +55(92)90330-9232
5    1  1 97116-7190
7   +55 41 713695594

❌ CEP - 669 inválidos

            cep
3       4895343
4  1  9374-5229
5    2941ì3-186
8   1  0205-395
9   7  5254-599

❌ DATA - 720 inválidos

            data
0     331/07/203
1      33/6/1994
2    13//11/2005
3  3  9/088/2029
4   1  9/02/2005

❌ VALOR - 969 inválidos

            valor
0    R$5 3.553,18
1         141.556
2        _1,371.3
3  R  $  3.497,38
4       R$ 777.92

In [ ]:
!pip install unidecode

Requirement already satisfied: unidecode in /usr/local/lib/python3.12/dist-packages (1.4.0)

In [ ]:
# ============================================
# 🧠 Etapas 3 e 4 — Normalização e Validação
# Autor: Jefté Damaceno de Moura
# ============================================

import pandas as pd
import re
from datetime import datetime
import unicodedata
import numpy as np

# ============================
# ETAPA 0 — CONFIGURAÇÃO INICIAL
# ============================

NOMES_COMUNS = {
    "ana", "maria", "joao", "luiz", "pedro", "paula", "fernanda", "carlos", "lucas",
    "juliana", "bruno", "marcos", "camila", "rafael", "beatriz", "gabriel", "larissa",
    "roberto", "rodrigo", "aline", "ricardo", "andre", "felipe", "carla"
}

SOBRENOMES_COMUNS = {
    "silva", "santos", "souza", "oliveira", "pereira", "lima", "rodrigues",
    "alves", "gomes", "ribeiro", "costa", "carvalho", "araujo", "melo",
    "barbosa", "castro", "martins", "dias", "teixeira", "freitas", "tavares",
    "machado", "moura", "nogueira", "fonseca", "pires", "campos", "coelho",
    "moreira", "almeida", "jesus", "cardoso"
}

def separar_nome_colado(nome: str) -> str:
    if not isinstance(nome, str) or not nome.strip():
        return nome
    nome = nome.lower().strip()
    for sobrenome in sorted(SOBRENOMES_COMUNS, key=len, reverse=True):
        if nome.endswith(sobrenome):
            prefixo = nome[:-len(sobrenome)]
            for n in sorted(NOMES_COMUNS, key=len, reverse=True):
                if prefixo.startswith(n):
                    return f"{n.capitalize()} {sobrenome.capitalize()}"
    for n1 in sorted(NOMES_COMUNS, key=len, reverse=True):
        if nome.startswith(n1):
            resto = nome[len(n1):]
            for n2 in sorted(NOMES_COMUNS, key=len, reverse=True):
                if resto.startswith(n2):
                    return f"{n1.capitalize()} {n2.capitalize()}"
    return nome.capitalize()

# ============================
# ETAPA 1 — LEITURA DO DATASET
# ============================

df = pd.read_csv('dataset_sintetico_regex_ruidos.csv')

print("📊 Dados originais:")
display(df.head())

# ============================
# ETAPA 3 — NORMALIZAÇÃO
# ============================

def limpar_numericos(campo):
    if pd.isna(campo):
        return ""
    return re.sub(r'[^0-9]', '', str(campo))

def limpar_nome(nome):
    if pd.isna(nome):
        return nome
    nome = re.sub(r'(\b\w)\s+(\w\b)', r'\1\2', nome)
    nome = re.sub(r'([a-z])([A-ZÁÉÍÓÚÂÊÔÃÕÇ])', r'\1 \2', nome)
    nome = nome.strip()
    nome = separar_nome_colado(nome)
    nome = ' '.join([n.capitalize() for n in nome.split()])
    return nome.strip()

# ============================
# CPF / CNPJ / TELEFONE
# ============================

def normaliza_cpf(cpf):
    """Formata CPF para XXX.XXX.XXX-YY sem alterar os dígitos. Se inválido → NaN"""
    if pd.isna(cpf):
        return np.nan
    cpf_limpo = limpar_numericos(cpf)
    if len(cpf_limpo) == 11:
        return f"{cpf_limpo[:3]}.{cpf_limpo[3:6]}.{cpf_limpo[6:9]}-{cpf_limpo[9:]}"
    else:
        return np.nan

# def normaliza_cnpj(cnpj):
#     """Formata CNPJ para XX.XXX.XXX/0001-YY sem alterar dígitos. Se inválido → NaN"""
#     if pd.isna(cnpj):
#         return np.nan
#     cnpj_limpo = limpar_numericos(cnpj)
#     if len(cnpj_limpo) == 14:
#         # Mantém a raiz e sufixo originais
#         return f"{cnpj_limpo[:2]}.{cnpj_limpo[2:5]}.{cnpj_limpo[5:8]}/{cnpj_limpo[8:12]}-{cnpj_limpo[12:]}"
#     else:
#         return np.nan
def normaliza_cnpj(cnpj):
    """Padroniza CNPJ mesmo com pequenos ruídos — mantém dígitos originais, se possível."""
    if pd.isna(cnpj):
        return np.nan
    cnpj_limpo = limpar_numericos(cnpj)
    if len(cnpj_limpo) < 13 or len(cnpj_limpo) > 15:
        return np.nan  # rejeita se for absurdo
    # Corrige se tiver 13 ou 15 dígitos (provável erro de digitação)
    if len(cnpj_limpo) == 13:
        cnpj_limpo = "0" + cnpj_limpo
    elif len(cnpj_limpo) == 15:
        cnpj_limpo = cnpj_limpo[:14]
    # Formata padrão
    try:
        return f"{cnpj_limpo[:2]}.{cnpj_limpo[2:5]}.{cnpj_limpo[5:8]}/{cnpj_limpo[8:12]}-{cnpj_limpo[12:]}"
    except:
        return np.nan

def normaliza_fone(fone):
    """Padroniza telefone para (XX) 9XXXX-XXXX"""
    if pd.isna(fone):
        return fone
    fone = limpar_numericos(fone)
    if len(fone) == 11:
        return f"({fone[:2]}) {fone[2:3]}{fone[3:7]}-{fone[7:]}"
    elif len(fone) == 10:
        return f"({fone[:2]}) {fone[2:6]}-{fone[6:]}"
    else:
        return np.nan

# ============================
# DATAS — corrigir e padronizar
# ============================

def normaliza_data(data):
    """Corrige e padroniza datas comuns no formato DD-MM-YYYY."""
    if pd.isna(data):
        return np.nan
    data_str = str(data).strip()
    data_str = re.sub(r'[^0-9/.-]', '', data_str)  # remove letras
    data_str = re.sub(r'//+', '/', data_str)        # corrige barras duplas
    data_str = re.sub(r'\s+', '', data_str)         # remove espaços
    data_str = data_str.replace('.', '/')           # troca pontos por barras

    # tenta adicionar zeros faltantes em dia/mês
    partes = re.split(r'[-/]', data_str)
    if len(partes) == 3:
        dia, mes, ano = partes
        if len(dia) == 1: dia = dia.zfill(2)
        if len(mes) == 1: mes = mes.zfill(2)
        if len(ano) == 2: ano = "20" + ano  # ex: 05 -> 2005
        data_str = f"{dia}/{mes}/{ano}"

    formatos = ["%d/%m/%Y", "%d-%m-%Y", "%Y-%m-%d"]
    for fmt in formatos:
        try:
            dt = datetime.strptime(data_str, fmt)
            return dt.strftime("%d-%m-%Y")
        except:
            pass
    return np.nan


# ============================
# OUTRAS FUNÇÕES
# ============================

def normaliza_email(email):
    if pd.isna(email):
        return np.nan
    email = str(email).strip().lower()
    email = re.sub(r'\s+', '', email)
    return email if "@" in email else np.nan

def normaliza_url(url):
    if pd.isna(url):
        return np.nan
    url = str(url).strip().lower()
    if not url.startswith("http"):
        url = "https://" + url
    return url

def normaliza_valor(valor):
    if pd.isna(valor):
        return np.nan
    valor_str = str(valor)
    valor_str = re.sub(r'[^\d,.-]', '', valor_str)
    valor_str = valor_str.replace('.', '').replace(',', '.')
    try:
        return round(float(valor_str), 2)
    except:
        return np.nan

def normaliza_texto_livre(txt):
    if pd.isna(txt):
        return np.nan
    txt = str(txt).strip()
    txt = unicodedata.normalize('NFKD', txt)
    txt = re.sub(r'[^A-Za-z0-9\s.,;!?-]', '', txt)
    txt = re.sub(r'\s+', ' ', txt)
    return txt.strip().capitalize()

# ============================
# APLICAÇÃO
# ============================

if 'nome' in df.columns:
    df['nome'] = df['nome'].apply(limpar_nome)
if 'cpf' in df.columns:
    df['cpf_normalizado'] = df['cpf'].apply(normaliza_cpf)
if 'cnpj' in df.columns:
    df['cnpj_normalizado'] = df['cnpj'].apply(normaliza_cnpj)
if 'telefone' in df.columns:
    df['telefone_normalizado'] = df['telefone'].apply(normaliza_fone)
if 'data' in df.columns:
    df['data_normalizada'] = df['data'].apply(normaliza_data)
if 'email' in df.columns:
    df['email_normalizado'] = df['email'].apply(normaliza_email)
if 'url' in df.columns:
    df['url_normalizada'] = df['url'].apply(normaliza_url)
if 'valor' in df.columns:
    df['valor_normalizado'] = df['valor'].apply(normaliza_valor)
if 'texto_livre' in df.columns:
    df['texto_livre_normalizado'] = df['texto_livre'].apply(normaliza_texto_livre)

print("✅ Dados após normalização completa:")
display(df.head())

# ============================
# ETAPA 4 — VALIDAÇÃO
# ============================

def validar_cpf(cpf):
    cpf = limpar_numericos(cpf)
    if len(cpf) != 11 or cpf == cpf[0] * 11:
        return False
    soma1 = sum(int(cpf[i]) * (10 - i) for i in range(9))
    d1 = (soma1 * 10 % 11) % 10
    soma2 = sum(int(cpf[i]) * (11 - i) for i in range(10))
    d2 = (soma2 * 10 % 11) % 10
    return d1 == int(cpf[9]) and d2 == int(cpf[10])

def validar_cnpj(cnpj):
    cnpj = limpar_numericos(cnpj)
    if len(cnpj) != 14:
        return False
    pesos1 = [5,4,3,2,9,8,7,6,5,4,3,2]
    pesos2 = [6] + pesos1
    soma1 = sum(int(cnpj[i]) * pesos1[i] for i in range(12))
    d1 = 11 - soma1 % 11
    if d1 >= 10: d1 = 0
    soma2 = sum(int(cnpj[i]) * pesos2[i] for i in range(13))
    d2 = 11 - soma2 % 11
    if d2 >= 10: d2 = 0
    return d1 == int(cnpj[12]) and d2 == int(cnpj[13])

if 'cpf_normalizado' in df.columns:
    df.loc[~df['cpf_normalizado'].apply(lambda x: validar_cpf(x) if pd.notna(x) else False), 'cpf_normalizado'] = np.nan
if 'cnpj_normalizado' in df.columns:
    df.loc[~df['cnpj_normalizado'].apply(lambda x: validar_cnpj(x) if pd.notna(x) else False), 'cnpj_normalizado'] = np.nan

print("📋 Validação de CPFs e CNPJs finalizada:")
display(df[['cpf_normalizado', 'cnpj_normalizado']].head())

# ============================
# ETAPA 5 — EXPORTAÇÃO
# ============================

df.to_csv('dados_ajustados.csv', index=False)
print("\n💾 Arquivo salvo como 'dados_ajustados.csv'")

📊 Dados originais:

,nome,email,telefone,cpf,cnpj,cep,data,valor,url,texto_livre
0,Danielë Souza,o ig8f_1c@example.com,(71) 959440-7816,999.9299.9999-99,86.379.402/6542-35,84959-310,331/07/203,"R$5 3.553,18",http://site.org/3xkxw/rek8,Cliente: Danielë Souza Contato: o ig8f_1c@exam...
1,S érgi8 Rodrigues,87a+u5b@,+55 71 57871ê331,43039117b122,2 27824-9638308,09839301,33/6/1994,141.556,h ttps://exemplo.com/n8i4p4/mgg1w11/3dgdzv,Cliente: S érgi8 Rodrigues Contato: 87a+u5b@ |...
2,H elena Costa,3uea3-.geû@ufc.br,3191824-4935,5555555555,54278498084187,48740164,13//11/2005,"_1,371.3",http://sitee.org/919ah,Cliente: H elena Costa Contato: 3uea3-.geû@ufc...
3,Yasmin Martins,c1a7mx1e@gmail com,(98) 95777-3872,951.484.656-70,36.629.946/8044-38,4895343,3 9/088/2029,"R $ 3.497,38",http://site.orrg/my5zpj/g1o,Cliente: Yasmin Martins Contato: c1a7mx1e@gmai...
4,Natan Azevedo,-8bz_.b@example.com,+55(92)90330-9232,272.0946.537-26,64641708053143,1 9374-5229,1 9/02/2005,R$ 777.92,https://contato.me/bty/mepgth,Cliente: Natan Azevedo Contato: -8bz_.b@exampl...

✅ Dados após normalização completa:

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,nome,email,telefone,cpf,cnpj,cep,data,valor,url,texto_livre,cpf_normalizado,cnpj_normalizado,telefone_normalizado,data_normalizada,email_normalizado,url_normalizada,valor_normalizado,texto_livre_normalizado
0,Danielë Souza,o ig8f_1c@example.com,(71) 959440-7816,999.9299.9999-99,86.379.402/6542-35,84959-310,331/07/203,"R$5 3.553,18",http://site.org/3xkxw/rek8,Cliente: Danielë Souza Contato: o ig8f_1c@exam...,NaN,86.379.402/6542-35,NaN,NaN,oig8f_1c@example.com,http://site.org/3xkxw/rek8,53553.18,Cliente daniele souza contato o ig8f1cexample....
1,S Érgi8 Rodrigues,87a+u5b@,+55 71 57871ê331,43039117b122,2 27824-9638308,09839301,33/6/1994,141.556,h ttps://exemplo.com/n8i4p4/mgg1w11/3dgdzv,Cliente: S érgi8 Rodrigues Contato: 87a+u5b@ |...,430.391.171-22,02.278.249/6383-08,NaN,NaN,87a+u5b@,https://h ttps://exemplo.com/n8i4p4/mgg1w11/3...,141556.00,Cliente s ergi8 rodrigues contato 87au5b 55 71...
2,H Elena Costa,3uea3-.geû@ufc.br,3191824-4935,5555555555,54278498084187,48740164,13//11/2005,"_1,371.3",http://sitee.org/919ah,Cliente: H elena Costa Contato: 3uea3-.geû@ufc...,NaN,54.278.498/0841-87,(31) 91824-4935,13-11-2005,3uea3-.geû@ufc.br,http://sitee.org/919ah,1.37,Cliente h elena costa contato 3uea3-.geuufc.br...
3,Yasmin Martins,c1a7mx1e@gmail com,(98) 95777-3872,951.484.656-70,36.629.946/8044-38,4895343,3 9/088/2029,"R $ 3.497,38",http://site.orrg/my5zpj/g1o,Cliente: Yasmin Martins Contato: c1a7mx1e@gmai...,951.484.656-70,36.629.946/8044-38,(98) 95777-3872,NaN,c1a7mx1e@gmailcom,http://site.orrg/my5zpj/g1o,3497.38,Cliente yasmin martins contato c1a7mx1egmail c...
4,Natan Azevedo,-8bz_.b@example.com,+55(92)90330-9232,272.0946.537-26,64641708053143,1 9374-5229,1 9/02/2005,R$ 777.92,https://contato.me/bty/mepgth,Cliente: Natan Azevedo Contato: -8bz_.b@exampl...,NaN,64.641.708/0531-43,NaN,19-02-2005,-8bz_.b@example.com,https://contato.me/bty/mepgth,77792.00,Cliente natan azevedo contato -8bz.bexample.co...

📋 Validação de CPFs e CNPJs finalizada:

  cpf_normalizado    cnpj_normalizado
0             NaN                 NaN
1  430.391.171-22                 NaN
2             NaN  54.278.498/0841-87
3  951.484.656-70  36.629.946/8044-38
4             NaN  64.641.708/0531-43

💾 Arquivo salvo como 'dados_ajustados.csv'

In [ ]:
print(df['cnpj_normalizado'].head(10))
print(df['data_normalizada'].head(10))

0                   NaN
1                   NaN
2    54.278.498/0841-87
3    36.629.946/8044-38
4    64.641.708/0531-43
5                   NaN
6                   NaN
7    74.821.759/4647-55
8                   NaN
9    99.809.402/4455-67
Name: cnpj_normalizado, dtype: object
0           NaN
1           NaN
2    13-11-2005
3           NaN
4    19-02-2005
5    14-02-2010
6    19-10-2022
7    28-04-2010
8    07-09-2005
9           NaN
Name: data_normalizada, dtype: object

In [ ]:
# =======================================================
# 🧠 Comparação entre Datasets — Antes x Depois da Limpeza
# =======================================================

import pandas as pd
import re
import numpy as np

# ============================
# ETAPA 0 — CARREGAMENTO
# ============================

# Dataset original (antes da limpeza)
df_original = pd.read_csv('dataset_sintetico_regex_ruidos.csv')

# Dataset ajustado (após normalização e validação)
df_limpo = pd.read_csv('dados_ajustados.csv')

print("📊 Visualização dos dados originais:")
display(df_original.head())

print("📊 Visualização dos dados ajustados:")
display(df_limpo.head())

# ============================
# ETAPA 1 — MAPEAMENTO DE COLUNAS
# ============================

# Define pares de comparação (coluna original → coluna ajustada)
mapeamento_colunas = {
    "cpf": "cpf_normalizado",
    "cnpj": "cnpj_normalizado",
    "telefone": "telefone_normalizado",
    "email": "email_normalizado",
    "url": "url_normalizada",
    "valor": "valor_normalizado",
    "data": "data_normalizada",
    "texto_livre": "texto_livre_normalizado",
    "nome": "nome"  # mesmo nome em ambos
}

# Filtra apenas colunas existentes em ambos
pares_validos = {
    orig: novo for orig, novo in mapeamento_colunas.items()
    if orig in df_original.columns and novo in df_limpo.columns
}

print(f"\n🔗 Colunas comparadas: {pares_validos}\n")

# ============================
# ETAPA 2 — COMPARAÇÃO DIRETA
# ============================

comparacao = pd.DataFrame()

for orig, novo in pares_validos.items():
    comparacao[f"{orig}_original"] = df_original[orig].astype(str).str.strip()
    comparacao[f"{orig}_ajustado"] = df_limpo[novo].astype(str).str.strip()
    comparacao[f"{orig}_igual"] = comparacao[f"{orig}_original"].eq(comparacao[f"{orig}_ajustado"])

# Mostra apenas registros com diferenças
diferencas = comparacao.loc[~comparacao.filter(like='_igual').all(axis=1)]

print("\n📋 DIFERENÇAS ENTRE OS DATASETS:")
display(diferencas.head(20))

# ============================
# ETAPA 3 — RESUMO DAS DIFERENÇAS
# ============================

print("\n📈 RESUMO DAS DIFERENÇAS:")
for orig, novo in pares_validos.items():
    iguais = comparacao[f"{orig}_igual"].sum()
    total = len(comparacao)
    diferentes = total - iguais
    pct = (diferentes / total) * 100
    print(f"🧩 {orig}: {diferentes}/{total} ({pct:.1f}%) valores diferentes")

# ============================
# ETAPA 4 — ANÁLISE DE QUALIDADE (REGEX)
# ============================

# Padrões atualizados conforme a nova normalização
padroes = {
    "nome": r"^[A-ZÁÉÍÓÚÂÊÔÃÕÇ][a-záéíóúâêôãõç]+(\s[A-ZÁÉÍÓÚÂÊÔÃÕÇ][a-záéíóúâêôãõç]+)+$",
    "cpf_normalizado": r"^\d{3}\.\d{3}\.\d{3}-\d{2}$",
    "cnpj_normalizado": r"^\d{2}\.\d{3}\.\d{3}/\d{4}-\d{2}$",
    "email_normalizado": r"^[\w\.-]+@[\w\.-]+\.\w+$",
    "telefone_normalizado": r"^\(\d{2}\)\s9\d{4}-\d{4}$",
    "cep": r"^\d{5}-\d{3}$",
    "data_normalizada": r"^\d{2}-\d{2}-\d{4}$",
    "valor_normalizado": r"^\d+(\.\d{2})?$"
}

def testar_regex(df, coluna, padrao):
    return df[coluna].apply(lambda x: bool(re.fullmatch(padrao, str(x).strip())) if pd.notna(x) else False)

print("\n📊 RELATÓRIO DE VALIDAÇÃO (ANTES x DEPOIS):")
for orig, novo in pares_validos.items():
    padrao = padroes.get(novo, None)
    if padrao:
        valid_orig = testar_regex(df_original, orig, padrao)
        valid_novo = testar_regex(df_limpo, novo, padrao)
        print(f"\n🔎 {orig.upper()}:")
        print(f"Antes: {valid_orig.sum()} válidos / {len(valid_orig)} ({valid_orig.mean()*100:.1f}%)")
        print(f"Depois: {valid_novo.sum()} válidos / {len(valid_novo)} ({valid_novo.mean()*100:.1f}%)")

# ============================
# ETAPA 5 — EXPORTAÇÃO OPCIONAL
# ============================

diferencas.to_csv('comparacao_datasets.csv', index=False)
print("\n💾 Arquivo de diferenças salvo como 'comparacao_datasets.csv'")

📊 Visualização dos dados originais:

,nome,email,telefone,cpf,cnpj,cep,data,valor,url,texto_livre
0,Danielë Souza,o ig8f_1c@example.com,(71) 959440-7816,999.9299.9999-99,86.379.402/6542-35,84959-310,331/07/203,"R$5 3.553,18",http://site.org/3xkxw/rek8,Cliente: Danielë Souza Contato: o ig8f_1c@exam...
1,S érgi8 Rodrigues,87a+u5b@,+55 71 57871ê331,43039117b122,2 27824-9638308,09839301,33/6/1994,141.556,h ttps://exemplo.com/n8i4p4/mgg1w11/3dgdzv,Cliente: S érgi8 Rodrigues Contato: 87a+u5b@ |...
2,H elena Costa,3uea3-.geû@ufc.br,3191824-4935,5555555555,54278498084187,48740164,13//11/2005,"_1,371.3",http://sitee.org/919ah,Cliente: H elena Costa Contato: 3uea3-.geû@ufc...
3,Yasmin Martins,c1a7mx1e@gmail com,(98) 95777-3872,951.484.656-70,36.629.946/8044-38,4895343,3 9/088/2029,"R $ 3.497,38",http://site.orrg/my5zpj/g1o,Cliente: Yasmin Martins Contato: c1a7mx1e@gmai...
4,Natan Azevedo,-8bz_.b@example.com,+55(92)90330-9232,272.0946.537-26,64641708053143,1 9374-5229,1 9/02/2005,R$ 777.92,https://contato.me/bty/mepgth,Cliente: Natan Azevedo Contato: -8bz_.b@exampl...

📊 Visualização dos dados ajustados:

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,nome,email,telefone,cpf,cnpj,cep,data,valor,url,texto_livre,cpf_normalizado,cnpj_normalizado,telefone_normalizado,data_normalizada,email_normalizado,url_normalizada,valor_normalizado,texto_livre_normalizado
0,Danielë Souza,o ig8f_1c@example.com,(71) 959440-7816,999.9299.9999-99,86.379.402/6542-35,84959-310,331/07/203,"R$5 3.553,18",http://site.org/3xkxw/rek8,Cliente: Danielë Souza Contato: o ig8f_1c@exam...,NaN,NaN,NaN,NaN,oig8f_1c@example.com,http://site.org/3xkxw/rek8,53553.18,Cliente daniele souza contato o ig8f1cexample....
1,S Érgi8 Rodrigues,87a+u5b@,+55 71 57871ê331,43039117b122,2 27824-9638308,09839301,33/6/1994,141.556,h ttps://exemplo.com/n8i4p4/mgg1w11/3dgdzv,Cliente: S érgi8 Rodrigues Contato: 87a+u5b@ |...,430.391.171-22,NaN,NaN,NaN,87a+u5b@,https://h ttps://exemplo.com/n8i4p4/mgg1w11/3...,141556.00,Cliente s ergi8 rodrigues contato 87au5b 55 71...
2,H Elena Costa,3uea3-.geû@ufc.br,3191824-4935,5555555555,54278498084187,48740164,13//11/2005,"_1,371.3",http://sitee.org/919ah,Cliente: H elena Costa Contato: 3uea3-.geû@ufc...,NaN,54.278.498/0841-87,(31) 91824-4935,13-11-2005,3uea3-.geû@ufc.br,http://sitee.org/919ah,1.37,Cliente h elena costa contato 3uea3-.geuufc.br...
3,Yasmin Martins,c1a7mx1e@gmail com,(98) 95777-3872,951.484.656-70,36.629.946/8044-38,4895343,3 9/088/2029,"R $ 3.497,38",http://site.orrg/my5zpj/g1o,Cliente: Yasmin Martins Contato: c1a7mx1e@gmai...,951.484.656-70,36.629.946/8044-38,(98) 95777-3872,NaN,c1a7mx1e@gmailcom,http://site.orrg/my5zpj/g1o,3497.38,Cliente yasmin martins contato c1a7mx1egmail c...
4,Natan Azevedo,-8bz_.b@example.com,+55(92)90330-9232,272.0946.537-26,64641708053143,1 9374-5229,1 9/02/2005,R$ 777.92,https://contato.me/bty/mepgth,Cliente: Natan Azevedo Contato: -8bz_.b@exampl...,NaN,64.641.708/0531-43,NaN,19-02-2005,-8bz_.b@example.com,https://contato.me/bty/mepgth,77792.00,Cliente natan azevedo contato -8bz.bexample.co...

🔗 Colunas comparadas: {'cpf': 'cpf_normalizado', 'cnpj': 'cnpj_normalizado', 'telefone': 'telefone_normalizado', 'email': 'email_normalizado', 'url': 'url_normalizada', 'valor': 'valor_normalizado', 'data': 'data_normalizada', 'texto_livre': 'texto_livre_normalizado', 'nome': 'nome'}


📋 DIFERENÇAS ENTRE OS DATASETS:

,cpf_original,cpf_ajustado,cpf_igual,cnpj_original,cnpj_ajustado,cnpj_igual,telefone_original,telefone_ajustado,telefone_igual,email_original,...,valor_igual,data_original,data_ajustado,data_igual,texto_livre_original,texto_livre_ajustado,texto_livre_igual,nome_original,nome_ajustado,nome_igual
0,999.9299.9999-99,nan,False,86.379.402/6542-35,nan,False,(71) 959440-7816,nan,False,o ig8f_1c@example.com,...,False,331/07/203,nan,False,Cliente: Danielë Souza Contato: o ig8f_1c@exam...,Cliente daniele souza contato o ig8f1cexample....,False,Danielë Souza,Danielë Souza,True
1,43039117b122,430.391.171-22,False,2 27824-9638308,nan,False,+55 71 57871ê331,nan,False,87a+u5b@,...,False,33/6/1994,nan,False,Cliente: S érgi8 Rodrigues Contato: 87a+u5b@ |...,Cliente s ergi8 rodrigues contato 87au5b 55 71...,False,S érgi8 Rodrigues,S Érgi8 Rodrigues,False
2,5555555555,nan,False,54278498084187,54.278.498/0841-87,False,3191824-4935,(31) 91824-4935,False,3uea3-.geû@ufc.br,...,False,13//11/2005,13-11-2005,False,Cliente: H elena Costa Contato: 3uea3-.geû@ufc...,Cliente h elena costa contato 3uea3-.geuufc.br...,False,H elena Costa,H Elena Costa,False
3,951.484.656-70,951.484.656-70,True,36.629.946/8044-38,36.629.946/8044-38,True,(98) 95777-3872,(98) 95777-3872,True,c1a7mx1e@gmail com,...,False,3 9/088/2029,nan,False,Cliente: Yasmin Martins Contato: c1a7mx1e@gmai...,Cliente yasmin martins contato c1a7mx1egmail c...,False,Yasmin Martins,Yasmin Martins,True
4,272.0946.537-26,nan,False,64641708053143,64.641.708/0531-43,False,+55(92)90330-9232,nan,False,-8bz_.b@example.com,...,False,1 9/02/2005,19-02-2005,False,Cliente: Natan Azevedo Contato: -8bz_.b@exampl...,Cliente natan azevedo contato -8bz.bexample.co...,False,Natan Azevedo,Natan Azevedo,True
5,989.413.435-18,989.413.435-18,True,40.084.271/0947-77,nan,False,1 1 97116-7190,(11) 97116-7190,False,hmuh8lmn@mail.com,...,False,14/02/2010,14-02-2010,False,Cliente: Paulo osta Contato: hmuh8lmn@mail.com...,Cliente paulo osta contato hmuh8lmnmail.com 1 ...,False,Paulo osta,Paulo Osta,False
6,876.038.597-94,876.038.597-94,True,3 4.824.771/0322-96,nan,False,11913171274,(11) 91317-1274,False,sz9c3fuquhz6@outlook.com,...,False,19/10/20õ22,19-10-2022,False,Cliente: Fernanda Ribeiro Contato: sz9c3fuquhz...,Cliente fernanda ribeiro contato sz9c3fuquhz6o...,False,Fernanda Ribeiro,Fernanda Ribeiro,True
7,379.237.474-90,379.237.474-90,True,74821759464755-,74.821.759/4647-55,False,+55 41 713695594,nan,False,70.lkklf-@outlook.com,...,False,2 8/04/2010,28-04-2010,False,Cliente: M arin Ribeiro Contato: 70.lkklf-@out...,Cliente m arin ribeiro contato 70.lkklf-outloo...,False,M arin Ribeiro,M Arin Ribeiro,False
8,351.585064-34,351.585.064-34,False,7 1.390.053/293j1-83,nan,False,41 92904-ô2284,(41) 92904-2284,False,_j0g5-0rcxn@dominio.org,...,False,07/09/2005,07-09-2005,False,Cliente: P aulo Ribeeiro Contato: _j0g5-0rcxn@...,Cliente p aulo ribeeiro contato j0g5-0rcxndomi...,False,P aulo Ribeeiro,P Aulo Ribeeiro,False
9,333333333333,nan,False,99.809.402/4ã455-67,99.809.402/4455-67,False,+65(31)96120-1836,nan,False,g.6nj4ogw@mail.comh,...,False,56/10v/1993,nan,False,Cliente: Beatriz Costa Contato: g.6nj4ogw@mail...,Cliente beatriz costa contato g.6nj4ogwmail.co...,False,Beatriz Costa,Beatriz Costa,True
10,477.005.411-40,477.005.411-40,True,79807935978231,79.807.935/9782-31,False,819551820377,nan,False,uj2e42tr_d@mail.cm,...,False,07/05/20e02,07-05-2002,False,Cliente: V inícius Carvalho Contato: uj2e42tr_...,Cliente v inicius carvalho contato uj2e42trdma...,False,V inícius Carvalho,V Inícius Carvalho,False
11,137.506.068-62,137.506.068-62,True,15.305.152/2047-6,nan,False,31 7790-1043,(31) 7790-1043,False,9g77hsfkr26@empresa.com.br,...,False,03/f07/2020,03-07-2020,False,Cliente: Beatriz Carvalho Contato: 9g77hsfkr26...,Cliente beatriz carvalho contato 9g77hsfkr26em...,False,Beatriz Carvalho,Beatriz Carvalho,True
12,40ä1658200241,nan,False,7 0..213.556/9092-71,70.213.556/9092-71,False,61 91928-5654,(61) 91928-5654,False,2 +1k2w2cw@,...,False,07/01/2020,07-01-2020,False,Cliente: Letícia Silva Contato: 2 +1k2w2cw@ | ...,Cliente leticia silva contato 2 1k2w2cw 61 919...,False,Letícia Silva,Letícia Silva,True
13,784.473.647-04,784.473.647-04,True,77.77.777/7777-77,nan,False,(61) 95556-2588,(61) 95556-2588,True,. cbfc.qn.0@uu(fc.br,...,False,25/03/2017,25-03-2017,False,Cliente: Yasmin Azevedo Contato: . cbfc.qn.0@u...,Cliente yasmin azevedo contato . cbfc.qn.0uufc...,False,Yasmin Azevedo,Yasmin Azevedo,True
14,9 72.896.230-45,972.896.230-45,False,307562636899771,nan,False,+ 55 95 g2885786,(55) 95288-5786,False,+ 4q_.@empresa.com.br,...,False,07/07/2012,07-07-2012,False,Cliente: Daniel Almeida Contato: + 4q_.@empres...,Cliente daniel almeida contato 4q.empresa.com....,False,Daniel Almeida,Daniel Almeida,True
15,296.685.161-92,296.685.161-92,True,3 3.333.333/3333-3,nan,False,71 945499045,(71) 94549-9045,False,rmhvk3qlavs.@gmail.com,...,False,26)/03/2013,26-03-2013,False,Cliente: Rafaela Lima Contato: rmhvk3qlavs.@gm...,Cliente rafaela lima contato rmhvk3qlavs.gmail...,False,Rafaela Lima,Rafael Lima,False
16,9y03.311.907-29,903.311.907-29,False,0 3.067õ.383/0284-66,03.067.383/0284-66,False,+55-(95)99953-4283,nan,False,p3wjrmhcoutlook.com,...,False,04/02/2017,04-02-2017,False,Cliente: T alita Almkeida Contato: p3wjrmhcout...,Cliente t alita almkeida contato p3wjrmhcoutlo...,False,T alita Almkeida,T Alita Almkeida,False
17,777.777.777-7,nan,False,97.700.886/0084-45,97.700.886/0084-45,True,51ä962118233,(51) 96211-8233,False,da0ioe@gmail.com,...,False,1 7/0220010,nan,False,Cliente: Sérgio Souza Contato: da0ioe@gmail.co...,Cliente sergio souza contato da0ioegmail.com 5...,False,Sérgio Souza,Sérgio Souza,True
18,183.982.622-30,183.982.622-30,True,21264644715327,nan,False,819371240-65,(81) 93712-4065,False,++uyas@dominio.org,...,False,0 3/01/2009,03-01-2009,False,Cliente: Ana Silva Contato: ++uyas@dominio.org...,Cliente ana silva contato uyasdominio.org 8193...,False,Ana Silva,Ana Silva,True
19,5 8.736.226-46,nan,False,379660033419134,nan,False,8595374785,(85) 9537-4785,False,etchbvgkp7@empresa.cm.br,...,False,5 /05/2013,05-05-2013,False,Cliente: P aulo Azevesdo Contato: etchbvgkp7@e...,Cliente p aulo azevesdo contato etchbvgkp7empr...,False,P aulo Azevesdo,P Aulo Azevesdo,False

📈 RESUMO DAS DIFERENÇAS:
🧩 cpf: 821/1000 (82.1%) valores diferentes
🧩 cnpj: 817/1000 (81.7%) valores diferentes
🧩 telefone: 924/1000 (92.4%) valores diferentes
🧩 email: 372/1000 (37.2%) valores diferentes
🧩 url: 329/1000 (32.9%) valores diferentes
🧩 valor: 1000/1000 (100.0%) valores diferentes
🧩 data: 980/1000 (98.0%) valores diferentes
🧩 texto_livre: 1000/1000 (100.0%) valores diferentes
🧩 nome: 378/1000 (37.8%) valores diferentes

📊 RELATÓRIO DE VALIDAÇÃO (ANTES x DEPOIS):

🔎 CPF:
Antes: 221 válidos / 1000 (22.1%)
Depois: 465 válidos / 1000 (46.5%)

🔎 CNPJ:
Antes: 233 válidos / 1000 (23.3%)
Depois: 492 válidos / 1000 (49.2%)

🔎 TELEFONE:
Antes: 48 válidos / 1000 (4.8%)
Depois: 248 válidos / 1000 (24.8%)

🔎 EMAIL:
Antes: 453 válidos / 1000 (45.3%)
Depois: 638 válidos / 1000 (63.8%)

🔎 VALOR:
Antes: 113 válidos / 1000 (11.3%)
Depois: 166 válidos / 1000 (16.6%)

🔎 DATA:
Antes: 22 válidos / 1000 (2.2%)
Depois: 564 válidos / 1000 (56.4%)

🔎 NOME:
Antes: 578 válidos / 1000 (57.8%)
Depois: 663 válidos / 1000 (66.3%)

💾 Arquivo de diferenças salvo como 'comparacao_datasets.csv'

# Charlingtonglaevionbeecheknavare